<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo e($report->title); ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4e73df;
            padding-bottom: 10px;
        }
        .header h1 {
            color: #4e73df;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .section {
            margin-bottom: 20px;
        }
        .section-title {
            color: #4e73df;
            font-size: 18px;
            margin-bottom: 10px;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8f9fc;
            color: #4e73df;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin-bottom: 20px;
        }
        .stat-box {
            background-color: #f8f9fc;
            padding: 15px;
            border-radius: 5px;
            text-align: center;
        }
        .stat-box h3 {
            margin: 0;
            color: #4e73df;
            font-size: 16px;
        }
        .stat-box p {
            margin: 5px 0 0;
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1><?php echo e($report->title); ?></h1>
        <p>Generated by: <?php echo e($report->generator->name); ?></p>
        <p>Generated at: <?php echo e($report->generated_at->format('M d, Y H:i')); ?></p>
    </div>

    <?php if($report->description): ?>
        <div class="section">
            <div class="section-title">Description</div>
            <p><?php echo e($report->description); ?></p>
        </div>
    <?php endif; ?>

    <div class="section">
        <div class="section-title">Report Data</div>
        <?php switch($report->type):
            case ('user_stats'): ?>
                <div class="stats-grid">
                    <div class="stat-box">
                        <h3>Total Users</h3>
                        <p><?php echo e($report->data['total_users']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>New Users</h3>
                        <p><?php echo e($report->data['new_users']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Active Users</h3>
                        <p><?php echo e($report->data['active_users']); ?></p>
                    </div>
                </div>

                <div class="section-title">Users by Role</div>
                <table>
                    <thead>
                        <tr>
                            <th>Role</th>
                            <th>Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $__currentLoopData = $report->data['users_by_role']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <td><?php echo e($role); ?></td>
                                <td><?php echo e($count); ?></td>
                            </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </tbody>
                </table>
                <?php break; ?>

            <?php case ('appointment_stats'): ?>
                <div class="stats-grid">
                    <div class="stat-box">
                        <h3>Total Appointments</h3>
                        <p><?php echo e($report->data['total_appointments']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Completed</h3>
                        <p><?php echo e($report->data['completed_appointments']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Cancelled</h3>
                        <p><?php echo e($report->data['cancelled_appointments']); ?></p>
                    </div>
                </div>

                <div class="section-title">Appointments by Doctor</div>
                <table>
                    <thead>
                        <tr>
                            <th>Doctor</th>
                            <th>Total Appointments</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $__currentLoopData = $report->data['appointments_by_doctor']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $doctor => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <td><?php echo e($doctor); ?></td>
                                <td><?php echo e($count); ?></td>
                            </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </tbody>
                </table>
                <?php break; ?>

            <?php case ('medical_stats'): ?>
                <div class="stats-grid">
                    <div class="stat-box">
                        <h3>Total Records</h3>
                        <p><?php echo e($report->data['total_records']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Record Types</h3>
                        <p><?php echo e(count($report->data['records_by_type'])); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Active Doctors</h3>
                        <p><?php echo e(count($report->data['records_by_doctor'])); ?></p>
                    </div>
                </div>

                <div class="section-title">Records by Type</div>
                <table>
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $__currentLoopData = $report->data['records_by_type']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <td><?php echo e(ucwords(str_replace('_', ' ', $type))); ?></td>
                                <td><?php echo e($count); ?></td>
                            </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </tbody>
                </table>

                <div class="section-title">Records by Doctor</div>
                <table>
                    <thead>
                        <tr>
                            <th>Doctor</th>
                            <th>Records</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $__currentLoopData = $report->data['records_by_doctor']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $doctor => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <td><?php echo e($doctor); ?></td>
                                <td><?php echo e($count); ?></td>
                            </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </tbody>
                </table>
                <?php break; ?>

            <?php case ('role_stats'): ?>
                <div class="stats-grid">
                    <div class="stat-box">
                        <h3>Total Roles</h3>
                        <p><?php echo e($report->data['total_roles']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Total Users</h3>
                        <p><?php echo e(array_sum($report->data['users_by_role'])); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Active Users</h3>
                        <p><?php echo e(array_sum($report->data['active_users_by_role'])); ?></p>
                    </div>
                </div>

                <div class="section-title">Users by Role</div>
                <table>
                    <thead>
                        <tr>
                            <th>Role</th>
                            <th>Total Users</th>
                            <th>Active Users</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $__currentLoopData = $report->data['users_by_role']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <td><?php echo e($role); ?></td>
                                <td><?php echo e($count); ?></td>
                                <td><?php echo e($report->data['active_users_by_role'][$role] ?? 0); ?></td>
                            </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </tbody>
                </table>
                <?php break; ?>

            <?php case ('system_stats'): ?>
                <div class="stats-grid">
                    <div class="stat-box">
                        <h3>Total Users</h3>
                        <p><?php echo e($report->data['total_users']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Total Appointments</h3>
                        <p><?php echo e($report->data['total_appointments']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Medical Records</h3>
                        <p><?php echo e($report->data['total_medical_records']); ?></p>
                    </div>
                </div>

                <div class="section-title">System Health</div>
                <table>
                    <thead>
                        <tr>
                            <th>Metric</th>
                            <th>Value</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Disk Usage</td>
                            <td><?php echo e(number_format($report->data['system_health']['disk_usage'], 1)); ?>%</td>
                            <td><?php echo e($report->data['system_health']['disk_usage'] > 80 ? 'Warning' : 'Healthy'); ?></td>
                        </tr>
                        <tr>
                            <td>Memory Usage</td>
                            <td><?php echo e(number_format($report->data['system_health']['memory_usage'], 1)); ?>%</td>
                            <td><?php echo e($report->data['system_health']['memory_usage'] > 80 ? 'Warning' : 'Healthy'); ?></td>
                        </tr>
                    </tbody>
                </table>
                <?php break; ?>

            <?php case ('patient_stats'): ?>
                <div class="stats-grid">
                    <div class="stat-box">
                        <h3>Total Patients</h3>
                        <p><?php echo e($report->data['total_patients']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>New Patients</h3>
                        <p><?php echo e($report->data['new_patients']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Active Patients</h3>
                        <p><?php echo e($report->data['active_patients']); ?></p>
                    </div>
                </div>

                <div class="section-title">Patient Overview</div>
                <table>
                    <thead>
                        <tr>
                            <th>Metric</th>
                            <th>Value</th>
                            <th>Percentage</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Total Patients</td>
                            <td><?php echo e($report->data['total_patients']); ?></td>
                            <td>100%</td>
                        </tr>
                        <tr>
                            <td>New Patients</td>
                            <td><?php echo e($report->data['new_patients']); ?></td>
                            <td><?php echo e(number_format(($report->data['new_patients'] / $report->data['total_patients']) * 100, 1)); ?>%</td>
                        </tr>
                        <tr>
                            <td>Active Patients</td>
                            <td><?php echo e($report->data['active_patients']); ?></td>
                            <td><?php echo e(number_format(($report->data['active_patients'] / $report->data['total_patients']) * 100, 1)); ?>%</td>
                        </tr>
                        <tr>
                            <td>Inactive Patients</td>
                            <td><?php echo e($report->data['total_patients'] - $report->data['active_patients']); ?></td>
                            <td><?php echo e(number_format((($report->data['total_patients'] - $report->data['active_patients']) / $report->data['total_patients']) * 100, 1)); ?>%</td>
                        </tr>
                    </tbody>
                </table>
                <?php break; ?>

            <?php case ('treatment_stats'): ?>
                <div class="stats-grid">
                    <div class="stat-box">
                        <h3>Total Treatments</h3>
                        <p><?php echo e($report->data['total_treatments']); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Treatment Types</h3>
                        <p><?php echo e(count($report->data['treatments_by_type'])); ?></p>
                    </div>
                    <div class="stat-box">
                        <h3>Success Rate</h3>
                        <p><?php echo e(number_format($report->data['success_rate'], 1)); ?>%</p>
                    </div>
                </div>

                <div class="section-title">Treatments by Type</div>
                <table>
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Count</th>
                            <th>Percentage</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $__currentLoopData = $report->data['treatments_by_type']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <tr>
                                <td><?php echo e(ucwords(str_replace('_', ' ', $type))); ?></td>
                                <td><?php echo e($count); ?></td>
                                <td><?php echo e(number_format(($count / $report->data['total_treatments']) * 100, 1)); ?>%</td>
                            </tr>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </tbody>
                </table>
                <?php break; ?>
        <?php endswitch; ?>
    </div>

    <div class="footer">
        <p>Generated by Hospital Management System</p>
        <p>Page 1 of 1</p>
    </div>
</body>
</html> <?php /**PATH C:\xampp\htdocs\dhms\resources\views/reports/pdf.blade.php ENDPATH**/ ?>