<?php $__env->startSection('content'); ?>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="mb-0"><?php echo e(__('Report Details: ')); ?> <?php echo e($report->title); ?></h5>
                        <a href="<?php echo e(route('doctor.reports.index')); ?>" class="btn btn-sm btn-outline-primary">
                            <i class="fas fa-arrow-left"></i> <?php echo e(__('Back to Reports List')); ?>

                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <?php if(session('success')): ?>
                        <div class="alert alert-success">
                            <?php echo e(session('success')); ?>

                        </div>
                    <?php endif; ?>

                    <div class="mb-3">
                        <strong><?php echo e(__('Title:')); ?></strong>
                        <p><?php echo e($report->title); ?></p>
                    </div>

                    <?php if($report->description): ?>
                        <div class="mb-3">
                            <strong><?php echo e(__('Description:')); ?></strong>
                            <p><?php echo e($report->description); ?></p>
                        </div>
                    <?php endif; ?>

                    <div class="mb-3">
                        <strong><?php echo e(__('Report Type:')); ?></strong>
                        <p><span class="badge bg-info"><?php echo e(ucwords(str_replace('_', ' ', $report->type))); ?></span></p>
                    </div>

                    <div class="mb-3">
                        <strong><?php echo e(__('Status:')); ?></strong>
                        <p><span class="badge bg-<?php echo e($report->status === 'completed' ? 'success' : 'warning'); ?>"><?php echo e(ucfirst($report->status)); ?></span></p>
                    </div>

                    <div class="mb-3">
                        <strong><?php echo e(__('Generated By:')); ?></strong>
                        <p><?php echo e($report->generator->name ?? 'N/A'); ?></p>
                    </div>

                    <div class="mb-3">
                        <strong><?php echo e(__('Generated At:')); ?></strong>
                        <p><?php echo e($report->generated_at ? $report->generated_at->format('M d, Y H:i:s') : 'N/A'); ?></p>
                    </div>
                    
                    <hr>

                    <h5 class="mt-4 mb-3"><?php echo e(__('Report Data')); ?></h5>
                    <?php if(!empty($report->data)): ?>
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">
                                <thead class="table-dark">
                                    <tr>
                                        <th>Statistic / Item</th>
                                        <th>Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $__currentLoopData = $report->data; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                        <tr>
                                            <td><?php echo e(ucwords(str_replace('_', ' ', $key))); ?></td>
                                            <td>
                                                <?php if($key === 'users_by_role' && (is_array($value) || is_object($value))): ?>
                                                    <ul class="mb-0">
                                                        <?php $__currentLoopData = $value; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                                            <li><strong><?php echo e($role); ?>:</strong> <?php echo e($count); ?></li>
                                                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                                                    </ul>
                                                <?php elseif(is_array($value) || is_object($value)): ?>
                                                    <pre><?php echo e(json_encode($value, JSON_PRETTY_PRINT)); ?></pre>
                                                <?php else: ?>
                                                    <?php echo e($value); ?>

                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                                </tbody>
                            </table>
                        </div>
                    <?php else: ?>
                        <p class="text-muted">No data available for this report.</p>
                    <?php endif; ?>

                </div>

                <div class="card-footer text-end">
                    <a href="<?php echo e(route('doctor.reports.download', $report)); ?>" class="btn btn-success">
                        <i class="fas fa-download"></i> <?php echo e(__('Download Report (PDF)')); ?>

                    </a>
                    <!-- Add Edit/Delete buttons here if needed, with appropriate authorization -->
                </div>
            </div>
        </div>
    </div>
</div>
<?php $__env->stopSection(); ?> 
<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\dhms\resources\views/reports/show.blade.php ENDPATH**/ ?>