@extends('layouts.app')

@section('title', 'Doctor Reports')

@section('content')
<div class="container py-5">
    <header class="text-center text-white mb-5">
        <h1 class="fw-bold">Reports</h1>
        <p class="lead">View and generate your reports here.</p>
    </header>
    <div class="text-end mb-4">
        <a href="{{ route('doctor.reports.create') }}" class="btn btn-primary">
            <i class="fas fa-plus"></i> Generate New Report
        </a>
    </div>
    <div class="card-custom animate">
        <div class="card-body">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            <div class="table-responsive">
                <table class="table table-hover table-dark table-bordered mb-0">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Type</th>
                            <th>Generated By</th>
                            <th>Generated At</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($reports as $report)
                            <tr>
                                <td>{{ $report->title }}</td>
                                <td>
                                    <span class="badge bg-info">
                                        {{ ucwords(str_replace('_', ' ', $report->type)) }}
                                    </span>
                                </td>
                                <td>{{ $report->generator->name }}</td>
                                <td>{{ $report->generated_at->format('M d, Y H:i') }}</td>
                                <td>
                                    <span class="badge bg-{{ $report->status === 'completed' ? 'success' : 'warning' }}">
                                        {{ ucfirst($report->status) }}
                                    </span>
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{ route('doctor.reports.show', $report) }}" 
                                           class="btn btn-sm btn-info">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a href="{{ route('doctor.reports.download', $report) }}" 
                                           class="btn btn-sm btn-success">
                                            <i class="fas fa-download"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6" class="text-center text-white">No reports found.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <div class="d-flex justify-content-center mt-4">
                {{ $reports->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
<style>
body.bg-dashboard {
    background: linear-gradient(to right, rgba(47, 102, 127, 0.7), rgba(0, 198, 255, 0.7)), url('/images/background.webp') no-repeat center center fixed;
    background-size: cover;
    min-height: 100vh;
}
.card-custom {
    background: rgba(0, 48, 80, 0.85);
    color: #ffffff;
    border: none;
    border-radius: 1rem;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2);
    transition: transform 0.5s ease, opacity 0.5s ease;
    opacity: 0;
    transform: translateY(40px);
}
.card-custom.animate {
    opacity: 1;
    transform: translateY(0);
}
h1.fw-bold, .lead, .text-white, .table-dark th, .table-dark td {
    color: #fff !important;
}
.table-dark {
    background-color: transparent;
}
</style>
@endpush

@push('body-class')
bg-dashboard
@endpush 