@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="mb-0">{{ __('Report Details: ') }} {{ $report->title }}</h5>
                        <a href="{{ route('doctor.reports.index') }}" class="btn btn-sm btn-outline-primary">
                            <i class="fas fa-arrow-left"></i> {{ __('Back to Reports List') }}
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    @if(session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <div class="mb-3">
                        <strong>{{ __('Title:') }}</strong>
                        <p>{{ $report->title }}</p>
                    </div>

                    @if($report->description)
                        <div class="mb-3">
                            <strong>{{ __('Description:') }}</strong>
                            <p>{{ $report->description }}</p>
                        </div>
                    @endif

                    <div class="mb-3">
                        <strong>{{ __('Report Type:') }}</strong>
                        <p><span class="badge bg-info">{{ ucwords(str_replace('_', ' ', $report->type)) }}</span></p>
                    </div>

                    <div class="mb-3">
                        <strong>{{ __('Status:') }}</strong>
                        <p><span class="badge bg-{{ $report->status === 'completed' ? 'success' : 'warning' }}">{{ ucfirst($report->status) }}</span></p>
                    </div>

                    <div class="mb-3">
                        <strong>{{ __('Generated By:') }}</strong>
                        <p>{{ $report->generator->name ?? 'N/A' }}</p>
                    </div>

                    <div class="mb-3">
                        <strong>{{ __('Generated At:') }}</strong>
                        <p>{{ $report->generated_at ? $report->generated_at->format('M d, Y H:i:s') : 'N/A' }}</p>
                    </div>
                    
                    <hr>

                    <h5 class="mt-4 mb-3">{{ __('Report Data') }}</h5>
                    @if(!empty($report->data))
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">
                                <thead class="table-dark">
                                    <tr>
                                        <th>Statistic / Item</th>
                                        <th>Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($report->data as $key => $value)
                                        <tr>
                                            <td>{{ ucwords(str_replace('_', ' ', $key)) }}</td>
                                            <td>
                                                @if($key === 'users_by_role' && (is_array($value) || is_object($value)))
                                                    <ul class="mb-0">
                                                        @foreach($value as $role => $count)
                                                            <li><strong>{{ $role }}:</strong> {{ $count }}</li>
                                                        @endforeach
                                                    </ul>
                                                @elseif(is_array($value) || is_object($value))
                                                    <pre>{{ json_encode($value, JSON_PRETTY_PRINT) }}</pre>
                                                @else
                                                    {{ $value }}
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <p class="text-muted">No data available for this report.</p>
                    @endif

                </div>

                <div class="card-footer text-end">
                    <a href="{{ route('doctor.reports.download', $report) }}" class="btn btn-success">
                        <i class="fas fa-download"></i> {{ __('Download Report (PDF)') }}
                    </a>
                    <!-- Add Edit/Delete buttons here if needed, with appropriate authorization -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection 